<?php
//require("history.php");

?>

<html lang="eng">

<head>
    <title>Energy House</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300,400,500" rel="stylesheet">

</head>



<body>

<header>

    <h1>Energy House</h1>

</header>

<nav>

    <ul>
        <li class="collection_title"><a href="">Temp</a></li>
        <li class="collection_title"><a href="">Humidity</a></li>
        <li class="collection_title"><a href="">Air Pressure</a></li>
        <li class="collection_title"><a href="">Rain</a></li>
        <li class="collection_title"><a href="">Wind_S</a></li>
        <li class="collection_title"><a href="">wind_D</a></li>
        <li class="collection_title"><a href="">Solar</a></li>
    </ul>

</nav>

<section class="filter">

    <form action="" method="POST">
        <input type="range" min="1" max="20" step="1" value="1" id="foo" name="passengers" onchange='document.getElementById("bar").value = "Slider Value = " + document.getElementById("foo").value;'/>
        <input type="text" name="bar" id="bar" value="Slider Value = 1" disabled />
        <br />
        <input type=submit name="topLines" value=Top Lines />
        <input type=submit name="lastLines" value=Last Lines />

        <!--            <select name="Order" class="btn btn-default dropdown-toggle" data-toggle="dropdown">-->
        <!--                <option value="top_Lines">Top Lines</option>-->
        <!--                <option value="last_Lines">Last Lines</option>-->
        <!--            </select>-->
    </form>

</section>


<section class="container">


    <div class="temp_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>Temp</h3>

                <?php  getData(temp);?>

            </div>

        </div>
    </div>

    <div class="humidity_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>Humidity</h3>

                <?php  getData(humidity);?>

            </div>

        </div>
    </div>

    <div class="a_p_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>A P</h3>

                <?php  getData(air_pressure);?>

            </div>

        </div>
    </div>

    <div class="rain_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>rain</h3>

                <?php  getData(rain);?>

            </div>

        </div>
    </div>

    <div class="wind_d_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>Wind D</h3>

                <?php  getData(wind_d);?>

            </div>

        </div>
    </div>

    <div class="wind_s_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">

                <h3>wind S</h3>

                <?php  getData(wind_s);?>

            </div>

        </div>
    </div>

    <div class="solar_wrapper collection_wrapper">

        <div id="product_items_wrapper" class="three-col-wrapper">

            <div id="product_wrapper" class="three-col-item">


                <h3>Solar</h3>
                <?php  getData(solar);?>

            </div>

        </div>
    </div>


</section>

<section>

    <div id="history_wrapper">



        <div class="history_data">
            <h3>Temp</h3>
            <?php
            //require("history.php");
            getData(temp);
            ?>

        </div>

        <div class="history_data">
            <h3>Air Pressure</h3>
            <?php
            //require("history.php");
            getData(air_pressure);
            ?>
        </div>

        <div class="history_data">
            <h3>Wind Direction</h3>
            <?php
            //require("history.php");
            getData(wind_d);
            ?>

        </div>

        <div class="history_data">
            <h3>Wind Speed</h3>
            <?php
            //require("history.php");
            getData(wind_s);
            ?>

        </div>

        <div class="history_data">
            <h3>Solar</h3>
            <?php
            //require("history.php");
            getData(solar);
            ?>

        </div>

        <div class="history_data">
            <h3>Humidity</h3>
            <?php
            //require("history.php");
            getData(humidity);
            ?>

        </div>

        <div class="history_data">
            <h3>Rain</h3>
            <?php
            //require("history.php");
            getData(rain);
            ?>

        </div>

    </div>

    <button><a href="index.php">Main Page</a></button>


</section>


<footer>


</footer>
<script src="assets/js/jquery-3.1.1.min.js">
<script src="assets/js/functions.js">



</script>
</body>

</html>

