<?php ?>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <?php
        $host = "146.87.2.99";
        $port = "1883";
        date_default_timezone_set('Europe/London');
        $date_timezone = date_default_timezone_get();


        $mqtt = new phpMQTT($host, $port, "ClientID" . rand());

        if (!$mqtt->connect()) {
            exit(1);
        }

        $weather_factors = array("temp", "humidity", "air_pressure", "rain", "wind_s", "wind_d", "solar");

        foreach ($weather_factors as $factor) {
            $topics['/' . $factor] = array("qos" => 0, "function" => "procmsg");
        }

        $mqtt->subscribe($topics,0);
        while($mqtt->proc()){

        }
        $mqtt->close();
        function procmsg($topic,$msg){
            echo "Msg Recieved: ".date("h:i:sa")."\nTopic:{$topic}\n$msg\n";
        }
        ?>
    </form>
<?php ?>