<?php



?>


<html lang="en">
<head>


    <title>Energy House - Setpoints</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300,400,500" rel="stylesheet">
</head>


<body>

<header>

    <h1><a href="index.php">Energy House</a></h1>
    <h1><a href="history.php">History</a></h1>
    <h1><a href="setPoints.php">Set Points</a></h1>

</header>


<form action="setpoint.php" method="post">

    <select name="setPoints" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <option value="set_Point_1">Set Point 1</option>
        <option value="set_Point_2">Set Point 2</option>
        <option value="set_Point_3">Set Point 3</option>
        <option value="set_Point_4">Set Point 4</option>
    </select>

    <input type="number" name="desiredValue" value="1" min="1" max="100">
    <input type="submit" name="submit" value="Set Point">
</form>

<section>

    <div id="weather_wrapper">

        <div class="weather_data">
            <div class="factor_graph" id="temp_div">
            <!--get graph ($thermometer and $setpoint->getValue()                -->

            </div>
            <div class="current_factor">

                <p id="sp1_value">
                    <?php

                    if(isset($_SESSION['setpoint1Value']))
                    {
                        echo $_SESSION['setpoint1Value'];
                    }

                    ?>

                </p>
                <input type="hidden" name="tempData" max="<?php echo getData(temp); ?>">

                <div class="factor_meaning">
                    <h3 class="factor_measure">setpoint</h3>
                    <h3 class="factor_name">Setpoint 1</h3>
                </div>

                <!--<div class="download">
                    <input class="download_btn" type=submit name="download_temp" value=""/>


                </div>-->

            </div>
        </div>

        <div class="weather_data">
            <div class="factor_graph" id="temp_div">

            </div>
            <div class="current_factor">

                <p id="temp_value"><?php

                    if(isset($_SESSION['setpoint2Value']))
                    {
                        echo $_SESSION['setpoint2Value'];
                    }

                    ?></p>
                <input type="hidden" name="tempData" max="<?php echo getData(temp); ?>">

                <div class="factor_meaning">
                    <h3 class="factor_measure">setpoint</h3>
                    <h3 class="factor_name">Setpoint 2</h3>
                </div>

                <!--<div class="download">
                    <input class="download_btn" type=submit name="download_temp" value=""/>


                </div>-->

            </div>
        </div>

        <div class="weather_data">
            <div class="factor_graph" id="temp_div">

            </div>
            <div class="current_factor">

                <p id="temp_value"><?php

                    if(isset($_SESSION['setpoint3Value']))
                    {
                        echo $_SESSION['setpoint3Value'];
                    }

                    ?></p>
                <input type="hidden" name="tempData" max="<?php echo getData(temp); ?>">

                <div class="factor_meaning">
                    <h3 class="factor_measure">setpoint</h3>
                    <h3 class="factor_name">Setpoint 3</h3>
                </div>

                <!--<div class="download">
                    <input class="download_btn" type=submit name="download_temp" value=""/>


                </div>-->

            </div>
        </div>

        <div class="weather_data">
            <div class="factor_graph" id="temp_div">

            </div>
            <div class="current_factor">

                <p id="temp_value"><?php

                    if(isset($_SESSION['setpoint4Value']))
                    {
                        echo $_SESSION['setpoint4Value'];
                    }

                    ?></p>
                <input type="hidden" name="tempData" max="<?php echo getData(temp); ?>">

                <div class="factor_meaning">
                    <h3 class="factor_measure">setpoint</h3>
                    <h3 class="factor_name">Setpoint 4</h3>
                </div>

                <!--<div class="download">
                    <input class="download_btn" type=submit name="download_temp" value=""/>


                </div>-->

            </div>
        </div>

    </div>

</section>

<footer>


</footer>

</body>

</html>

