<?php

<form action="setpoint.php" method="post">

    <select name="setPoints" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <option name="set_Point_1">Set Point 1</option>
        <option value="set_Point_2">Set Point 2</option>
        <option value="set_Point_3">Set Point 3</option>
        <option value="set_Point_4">Set Point 4</option>
    </select>

    <input type="number" name="desiredValue" value="1" min="1" max="100">
    <input type="submit" name="submit" value="Set Point">
</form>